### PR TITLE
Make fragment fusion script compliant with multiple Open3D versions.

### PR DESCRIPTION
**Pull request by SergioRAgostinho**
The current PR addresses API changes that occurred in Open3D. Three important points to mention here:
- exposed the reduced name `o3d` to the entire because it's being used in more than one function scope.
- Open3D's version is checked only once and a proxy function object is assigned the correct function signature.
- I've checked the documentation on the website and `write_point_cloud` is always under `o3d.io` from 0.6.0 onward. There's no docs on the project's website for any version prior to it.

### CODE REVIEW

**Comment by XuyangBai** [comment]
Hi, thank you for your feedback. I didn't test the open3d with version later than 0.7 but line 22 should be 

```python
if LooseVersion(o3d.__version__) > LooseVersion("0.7.0.0"):
```
or the version 0.7.0.0 will be in the wrong branch

**Comment by SergioRAgostinho** [comment]
~~I am not witnessing that behaviour.~~
```python
>>> import open3d as o3d
>>> from distutils.version import LooseVersion
>>> o3d.__version__
'0.9.0.0'
>>> LooseVersion(o3d.__version__) >= LooseVersion("0.9")
True
>>> LooseVersion(o3d.__version__) >= LooseVersion("0.9.0.1")
False
>>> LooseVersion(o3d.__version__) >= LooseVersion("0.10")
False
>>> LooseVersion(o3d.__version__) >= LooseVersion("0.9.1.0")
False
>>> LooseVersion(o3d.__version__) >= LooseVersion("0.9.0.0")
True
>>> LooseVersion(o3d.__version__) >= LooseVersion("0.7.0.0")
True
>>> LooseVersion(o3d.__version__) >= LooseVersion("0.7")
True
```
~~What's your distutils version? Mine is 3.6.10.~~

Interesting. The inequality sign is key to the problem, you can see below.
```python
>>> LooseVersion(o3d.__version__) > LooseVersion("0.9")
True    # It should be false, but subject to interpretation.
>>> LooseVersion(o3d.__version__) > LooseVersion("0.9.0.1")
False
>>> LooseVersion(o3d.__version__) > LooseVersion("0.10")
False
>>> LooseVersion(o3d.__version__) > LooseVersion("0.9.1.0")
False
>>> LooseVersion(o3d.__version__) > LooseVersion("0.9.0.0")
False 
>>> LooseVersion(o3d.__version__) > LooseVersion("0.7.0.0")
True
>>> LooseVersion(o3d.__version__) > LooseVersion("0.7")
True
```
However in the patch I submitted I'm using `>=` and not `>`. Thus things are falling under the right branch. Do you still want me to modify the version to the complete semver string?

**Comment by XuyangBai** [comment]
@SergioRAgostinho   There might be something wrong with `distutil`.  In my environment, things go wrong if using `0.7.0.0` version. My `>=` and `>` return different values.
截屏2020-02-27下午5 34 21

Maybe just leave it as so, I use open3d 0.7.0.0 for my whole project and it takes time to make it all compliant with other versions.  Anyway, thank you so much !

**Comment by SergioRAgostinho** [comment]
> Maybe just leave it as so, I use open3d 0.7.0.0 for my whole project and it takes time to make it all compliant with other versions. Anyway, thank you so much !

No problem.

**Pull request closed without merging**
